### ISSUE TITLE
Update documentation to use correct images

### ISSUE THREAD

**Issue by mrapcooper** [aws-samples/amazon-managed-service-for-apache-flink-examples#77] opened 2024-11-20 12:08 UTC
### Purpose of the change
Update the documentation to use the correct AWS iconography.

### Verifying this change
This is a trivial documentation only change, updating the icons used.

### Significant changes
_(Please check any boxes [x] if the answer is "yes". You can first publish the PR and check them afterward, for convenience.)_
- [ ] Completely new example
- [ ] Updated an existing example to newer Flink version or dependencies versions
- [ ] Improved an existing example
- [ ] Modified the runtime configuration of an existing example (i.e. added/removed/modified any runtime properties)
- [ ] Modified the expected input or output of an existing example (e.g. modified the source or sink, modified the record schema)

**Comment by mrapcooper** [comment] 2024-11-20 12:26
this is a duplicate of 78

**Comment by hlteoh37** [comment] 2024-11-20 17:58
Duplicate of #78

**Closed by hlteoh37** 2024-11-20 17:58 UTC
